<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DeskMeter.Core.Data</RootNamespace>
    <AssemblyName>DeskMeter.Core.Mac</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeskMeter.Core\DeskMeter.Core.csproj" />
  </ItemGroup>
</Project>
