<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DeskMeter.Core</RootNamespace>
    <AssemblyName>DeskMeter.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.4" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.0" />
  </ItemGroup>
</Project>
